//------------------------------------------------------------------------------
// <auto-generated>
//     このｺーﾄﾞはﾂーﾙによって生成されました。
//     ﾗﾝﾀｲﾑ ﾊﾞーｼﾞｮﾝ:4.0.30319.42000
//
//     このﾌｧｲﾙへの変更は、以下の状況下で不正な動作の原因になったり、
//     ｺーﾄﾞが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motitter.Properties {
    using System;
    
    
    /// <summary>
    ///   ﾛーｶﾗｲｽﾞされた文字列などを検索するための、厳密に型指定されたﾘｿーｽ ｸﾗｽです。
    /// </summary>
    // このｸﾗｽは StronglyTypedResourceBuilder ｸﾗｽが ResGen
    // または Visual Studio のようなﾂーﾙを使用して自動生成されました。
    // ﾒﾝﾊﾞーを追加または削除するには、.ResX ﾌｧｲﾙを編集して、/str ｵﾌﾟｼｮﾝと共に
    // ResGen を実行し直すか、または VS ﾌﾟﾛｼﾞｪｸﾄをﾋﾞﾙﾄﾞし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このｸﾗｽで使用されているｷｬｯｼｭされた ResourceManager ｲﾝｽﾀﾝｽを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Motitter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのﾘｿーｽ ｸﾗｽを使用して、すべての検索ﾘｿーｽに対し、
        ///   現在のｽﾚｯﾄﾞの CurrentUICulture ﾌﾟﾛﾊﾟﾃｨをｵーﾊﾞーﾗｲﾄﾞします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のﾛーｶﾗｲｽﾞされたﾘｿーｽを検索します。
        /// </summary>
        internal static byte[] icon_xpm {
            get {
                object obj = ResourceManager.GetObject("icon_xpm", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
